import type { Portfolio } from "./types";

/** In-memory fixtures backing the V1 mock implementation. */
export const MOCK_PORTFOLIOS: Portfolio[] = [
  {
    id: "pf-001",
    type: "portfolio",
    label: "Smith Family Trust — Balanced",
    accountId: "ac-001",
    strategy: "Balanced 60/40",
    baseCurrency: "USD",
    marketValue: { amount: 4_250_000, currency: "USD" },
    holdingsCount: 42,
    dayChangePct: 0.42,
  },
  {
    id: "pf-002",
    type: "portfolio",
    label: "Smith Family Trust — Growth",
    accountId: "ac-001",
    strategy: "Global Equity Growth",
    baseCurrency: "USD",
    marketValue: { amount: 1_980_500, currency: "USD" },
    holdingsCount: 28,
    dayChangePct: -1.13,
  },
  {
    id: "pf-003",
    type: "portfolio",
    label: "Meridian Pension — Liability Matching",
    accountId: "ac-002",
    strategy: "LDI Fixed Income",
    baseCurrency: "GBP",
    marketValue: { amount: 87_400_000, currency: "GBP" },
    holdingsCount: 113,
    dayChangePct: 0.08,
  },
  {
    id: "pf-004",
    type: "portfolio",
    label: "Meridian Pension — Return Seeking",
    accountId: "ac-002",
    strategy: "Diversified Growth",
    baseCurrency: "GBP",
    marketValue: { amount: 41_220_000, currency: "GBP" },
    holdingsCount: 76,
    dayChangePct: 1.27,
  },
  {
    id: "pf-005",
    type: "portfolio",
    label: "Aurora Endowment — Core",
    accountId: "ac-003",
    strategy: "Multi-Asset Core",
    baseCurrency: "USD",
    marketValue: { amount: 152_900_000, currency: "USD" },
    holdingsCount: 204,
    dayChangePct: -0.34,
  },
  {
    id: "pf-006",
    type: "portfolio",
    label: "Aurora Endowment — Private Markets",
    accountId: "ac-003",
    strategy: "Private Equity / Alts",
    baseCurrency: "USD",
    marketValue: { amount: 63_500_000, currency: "USD" },
    holdingsCount: 31,
    dayChangePct: 0.0,
  },
  {
    id: "pf-007",
    type: "portfolio",
    label: "Lindqvist Holdings — EUR Income",
    accountId: "ac-004",
    strategy: "European Credit Income",
    baseCurrency: "EUR",
    marketValue: { amount: 12_840_000, currency: "EUR" },
    holdingsCount: 58,
    dayChangePct: 0.21,
  },
  {
    id: "pf-008",
    type: "portfolio",
    label: "Lindqvist Holdings — Tactical",
    accountId: "ac-004",
    strategy: "Tactical Macro",
    baseCurrency: "EUR",
    marketValue: { amount: 8_310_000, currency: "EUR" },
    holdingsCount: 19,
    dayChangePct: -2.46,
  },
  {
    id: "pf-009",
    type: "portfolio",
    label: "Cascade Family Office — ESG Equity",
    accountId: "ac-005",
    strategy: "Sustainable Global Equity",
    baseCurrency: "USD",
    marketValue: { amount: 29_760_000, currency: "USD" },
    holdingsCount: 64,
    dayChangePct: 1.92,
  },
  {
    id: "pf-010",
    type: "portfolio",
    label: "Cascade Family Office — Cash & Short Duration",
    accountId: "ac-005",
    strategy: "Short Duration Fixed Income",
    baseCurrency: "USD",
    marketValue: { amount: 18_050_000, currency: "USD" },
    holdingsCount: 22,
    dayChangePct: 0.03,
  },
  {
    id: "pf-011",
    type: "portfolio",
    label: "Okafor Trust — Emerging Markets",
    accountId: "ac-006",
    strategy: "EM Equity",
    baseCurrency: "USD",
    marketValue: { amount: 22_410_000, currency: "USD" },
    holdingsCount: 89,
    dayChangePct: -0.77,
  },
  {
    id: "pf-012",
    type: "portfolio",
    label: "Okafor Trust — Real Assets",
    accountId: "ac-006",
    strategy: "Infrastructure & REITs",
    baseCurrency: "USD",
    marketValue: { amount: 15_630_000, currency: "USD" },
    holdingsCount: 47,
    dayChangePct: 0.55,
  },
];

/** Simulate network latency so the mock feels real. */
export function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
